
// This file has been generated by the GUI designer. Do not modify.

public partial class AddStreamWindow
{
	private global::Gtk.HBox hbox5;
	private global::Gtk.Entry streamUserEntry;
	private global::Gtk.ComboBox streamTypeCombo;
	private global::Gtk.Label label1;
	private global::Gtk.Button buttonCancel;
	private global::Gtk.Button buttonOk;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget AddStreamWindow
		this.Name = "AddStreamWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Add Stream");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Internal child AddStreamWindow.VBox
		global::Gtk.VBox w1 = this.VBox;
		w1.Name = "dialog1_VBox";
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.streamUserEntry = new global::Gtk.Entry ();
		this.streamUserEntry.CanFocus = true;
		this.streamUserEntry.Name = "streamUserEntry";
		this.streamUserEntry.Text = global::Mono.Unix.Catalog.GetString ("Username / URL");
		this.streamUserEntry.IsEditable = true;
		this.streamUserEntry.ActivatesDefault = true;
		this.streamUserEntry.InvisibleChar = '●';
		this.hbox5.Add (this.streamUserEntry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.streamUserEntry]));
		w2.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.streamTypeCombo = global::Gtk.ComboBox.NewText ();
		this.streamTypeCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Justin.tv"));
		this.streamTypeCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Twitch.tv"));
		this.streamTypeCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Livestream.com"));
		this.streamTypeCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Ustream"));
		this.streamTypeCombo.AppendText (global::Mono.Unix.Catalog.GetString ("URL"));
		this.streamTypeCombo.CanDefault = true;
		this.streamTypeCombo.Name = "streamTypeCombo";
		this.streamTypeCombo.Active = 0;
		this.hbox5.Add (this.streamTypeCombo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.streamTypeCombo]));
		w3.Position = 1;
		w1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox5]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter the username of the stream you are adding. Example: http://justin.tv/<b>username</b>. Alternatively, paste a URL directly.");
		this.label1.UseMarkup = true;
		this.label1.Wrap = true;
		w1.Add (this.label1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.label1]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Internal child AddStreamWindow.ActionArea
		global::Gtk.HButtonBox w6 = this.ActionArea;
		w6.Name = "dialog1_ActionArea";
		w6.Spacing = 10;
		w6.BorderWidth = ((uint)(5));
		w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonCancel = new global::Gtk.Button ();
		this.buttonCancel.CanDefault = true;
		this.buttonCancel.CanFocus = true;
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.UseStock = true;
		this.buttonCancel.UseUnderline = true;
		this.buttonCancel.Label = "gtk-cancel";
		this.AddActionWidget (this.buttonCancel, -6);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonCancel]));
		w7.Expand = false;
		w7.Fill = false;
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonOk = new global::Gtk.Button ();
		this.buttonOk.CanDefault = true;
		this.buttonOk.CanFocus = true;
		this.buttonOk.Name = "buttonOk";
		this.buttonOk.UseUnderline = true;
		this.buttonOk.Label = global::Mono.Unix.Catalog.GetString ("_Add");
		this.AddActionWidget (this.buttonOk, -5);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOk]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 333;
		this.DefaultHeight = 127;
		this.Show ();
		this.buttonCancel.Clicked += new global::System.EventHandler (this.Cancel);
		this.buttonOk.Clicked += new global::System.EventHandler (this.OkAdd);
	}
}
