
// This file has been generated by the GUI designer. Do not modify.

public partial class EditPlayerWindow
{
	private global::Gtk.HBox hbox1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView playerTreeView;
	private global::Gtk.VButtonBox vbuttonbox1;
	private global::Gtk.FileChooserButton browseButton;
	private global::Gtk.Button commandButton;
	private global::Gtk.Button removeButton;
	private global::Gtk.Button buttonCancel;
	private global::Gtk.Button buttonOk;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget EditPlayerWindow
		this.Name = "EditPlayerWindow";
		this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Internal child EditPlayerWindow.VBox
		global::Gtk.VBox w1 = this.VBox;
		w1.Name = "dialog1_VBox";
		w1.BorderWidth = ((uint)(2));
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.playerTreeView = new global::Gtk.TreeView ();
		this.playerTreeView.CanFocus = true;
		this.playerTreeView.Name = "playerTreeView";
		this.playerTreeView.EnableSearch = false;
		this.GtkScrolledWindow.Add (this.playerTreeView);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.browseButton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a Media Player"), ((global::Gtk.FileChooserAction)(0)));
		this.browseButton.Name = "browseButton";
		this.vbuttonbox1.Add (this.browseButton);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.browseButton]));
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.commandButton = new global::Gtk.Button ();
		this.commandButton.CanFocus = true;
		this.commandButton.Name = "commandButton";
		this.commandButton.UseUnderline = true;
		this.commandButton.Label = global::Mono.Unix.Catalog.GetString ("Co_mmand...");
		this.vbuttonbox1.Add (this.commandButton);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.commandButton]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.removeButton = new global::Gtk.Button ();
		this.removeButton.CanFocus = true;
		this.removeButton.Name = "removeButton";
		this.removeButton.UseUnderline = true;
		this.removeButton.Label = global::Mono.Unix.Catalog.GetString ("_Remove");
		this.vbuttonbox1.Add (this.removeButton);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.removeButton]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.hbox1.Add (this.vbuttonbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbuttonbox1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		w1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
		w8.Position = 0;
		// Internal child EditPlayerWindow.ActionArea
		global::Gtk.HButtonBox w9 = this.ActionArea;
		w9.Name = "dialog1_ActionArea";
		w9.Spacing = 10;
		w9.BorderWidth = ((uint)(5));
		w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonCancel = new global::Gtk.Button ();
		this.buttonCancel.CanDefault = true;
		this.buttonCancel.CanFocus = true;
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.UseStock = true;
		this.buttonCancel.UseUnderline = true;
		this.buttonCancel.Label = "gtk-cancel";
		this.AddActionWidget (this.buttonCancel, -6);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonCancel]));
		w10.Expand = false;
		w10.Fill = false;
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonOk = new global::Gtk.Button ();
		this.buttonOk.CanDefault = true;
		this.buttonOk.CanFocus = true;
		this.buttonOk.Name = "buttonOk";
		this.buttonOk.UseStock = true;
		this.buttonOk.UseUnderline = true;
		this.buttonOk.Label = "gtk-ok";
		this.AddActionWidget (this.buttonOk, -5);
		global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonOk]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 281;
		this.DefaultHeight = 250;
		this.Show ();
		this.browseButton.SelectionChanged += new global::System.EventHandler (this.SelectedPlayer);
		this.commandButton.Clicked += new global::System.EventHandler (this.EnterCommand);
		this.removeButton.Clicked += new global::System.EventHandler (this.OnRemove);
		this.buttonCancel.Clicked += new global::System.EventHandler (this.OnCancel);
		this.buttonOk.Clicked += new global::System.EventHandler (this.OnOK);
	}
}
