
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action OpenURLAction;
	private global::Gtk.Action ExitAction;
	private global::Gtk.Action MediaPlayerAction;
	private global::Gtk.ToggleAction AlwaysOnTopAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.VBox vbox2;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.HBox hbox4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView streamList;
	private global::Gtk.VButtonBox vbuttonbox2;
	private global::Gtk.Button button2;
	private global::Gtk.Button button4;
	private global::Gtk.Fixed fixed11;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.Table table4;
	private global::Gtk.Button addPlayerButton;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.ComboBox mediaPlayerCombo;
	private global::Gtk.ComboBox qualityCombo;
	private global::Gtk.Label GtkLabel6;
	private global::Gtk.Statusbar stdOutStatus;
	private global::Gtk.Button watchButton;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, null);
		this.OpenURLAction = new global::Gtk.Action ("OpenURLAction", global::Mono.Unix.Catalog.GetString ("_Open URL..."), null, null);
		this.OpenURLAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open URL ...");
		w1.Add (this.OpenURLAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("_Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Exit");
		w1.Add (this.ExitAction, null);
		this.MediaPlayerAction = new global::Gtk.Action ("MediaPlayerAction", global::Mono.Unix.Catalog.GetString ("_Media Player"), null, null);
		this.MediaPlayerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Media Player");
		w1.Add (this.MediaPlayerAction, null);
		this.AlwaysOnTopAction = new global::Gtk.ToggleAction ("AlwaysOnTopAction", global::Mono.Unix.Catalog.GetString ("Always on Top"), null, null);
		this.AlwaysOnTopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Always on Top");
		w1.Add (this.AlwaysOnTopAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("_About..."), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About...");
		w1.Add (this.AboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("LiveStreamer");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-network", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='OpenURLAction' action='OpenURLAction'/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox2.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanDefault = true;
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 273;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.streamList = new global::Gtk.TreeView ();
		this.streamList.CanFocus = true;
		this.streamList.Name = "streamList";
		this.streamList.Reorderable = true;
		this.streamList.SearchColumn = 0;
		this.GtkScrolledWindow.Add (this.streamList);
		this.hbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow]));
		w4.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbuttonbox2 = new global::Gtk.VButtonBox ();
		this.vbuttonbox2.Name = "vbuttonbox2";
		this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		// Container child button2.Gtk.Container+ContainerChild
		global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w6 = new global::Gtk.HBox ();
		w6.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w7 = new global::Gtk.Image ();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		w6.Add (w7);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w9.LabelProp = global::Mono.Unix.Catalog.GetString ("_Add");
		w9.UseUnderline = true;
		w6.Add (w9);
		w5.Add (w6);
		this.button2.Add (w5);
		this.vbuttonbox2.Add (this.button2);
		global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.button2]));
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		// Container child button4.Gtk.Container+ContainerChild
		global::Gtk.Alignment w14 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w15 = new global::Gtk.HBox ();
		w15.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w16 = new global::Gtk.Image ();
		w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
		w15.Add (w16);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w18 = new global::Gtk.Label ();
		w18.LabelProp = global::Mono.Unix.Catalog.GetString ("_Remove");
		w18.UseUnderline = true;
		w15.Add (w18);
		w14.Add (w15);
		this.button4.Add (w14);
		this.vbuttonbox2.Add (this.button4);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.button4]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox4.Add (this.vbuttonbox2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbuttonbox2]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.hpaned1.Add (this.hbox4);
		global::Gtk.Paned.PanedChild w24 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.hbox4]));
		w24.Resize = false;
		w24.Shrink = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.fixed11 = new global::Gtk.Fixed ();
		this.fixed11.Name = "fixed11";
		this.fixed11.HasWindow = false;
		// Container child fixed11.Gtk.Fixed+FixedChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		this.GtkAlignment3.BorderWidth = ((uint)(3));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.table4 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.addPlayerButton = new global::Gtk.Button ();
		this.addPlayerButton.CanFocus = true;
		this.addPlayerButton.Name = "addPlayerButton";
		this.addPlayerButton.UseUnderline = true;
		// Container child addPlayerButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w25 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w26 = new global::Gtk.HBox ();
		w26.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w27 = new global::Gtk.Image ();
		w27.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
		w26.Add (w27);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w29 = new global::Gtk.Label ();
		w26.Add (w29);
		w25.Add (w26);
		this.addPlayerButton.Add (w25);
		this.table4.Add (this.addPlayerButton);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table4 [this.addPlayerButton]));
		w33.LeftAttach = ((uint)(2));
		w33.RightAttach = ((uint)(3));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table4.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Media Player");
		this.table4.Add (this.label2);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table4 [this.label2]));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Quality");
		this.table4.Add (this.label3);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table4 [this.label3]));
		w35.TopAttach = ((uint)(1));
		w35.BottomAttach = ((uint)(2));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.mediaPlayerCombo = global::Gtk.ComboBox.NewText ();
		this.mediaPlayerCombo.AppendText (global::Mono.Unix.Catalog.GetString ("vlc"));
		this.mediaPlayerCombo.AppendText (global::Mono.Unix.Catalog.GetString ("mplayer"));
		this.mediaPlayerCombo.Name = "mediaPlayerCombo";
		this.mediaPlayerCombo.Active = 0;
		this.table4.Add (this.mediaPlayerCombo);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table4 [this.mediaPlayerCombo]));
		w36.LeftAttach = ((uint)(1));
		w36.RightAttach = ((uint)(2));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.qualityCombo = global::Gtk.ComboBox.NewText ();
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("best"));
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("1080p+"));
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("1080p"));
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("720p+"));
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("720p"));
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("480p"));
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("360p"));
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("240p"));
		this.qualityCombo.AppendText (global::Mono.Unix.Catalog.GetString ("worst"));
		this.qualityCombo.Name = "qualityCombo";
		this.qualityCombo.Active = 0;
		this.table4.Add (this.qualityCombo);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table4 [this.qualityCombo]));
		w37.TopAttach = ((uint)(1));
		w37.BottomAttach = ((uint)(2));
		w37.LeftAttach = ((uint)(1));
		w37.RightAttach = ((uint)(2));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment3.Add (this.table4);
		this.frame3.Add (this.GtkAlignment3);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.WidthRequest = 200;
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.Xalign = 0F;
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("Options");
		this.GtkLabel6.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel6;
		this.fixed11.Add (this.frame3);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.frame3]));
		w40.X = 13;
		w40.Y = 4;
		this.hpaned1.Add (this.fixed11);
		this.vbox2.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hpaned1]));
		w42.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.stdOutStatus = new global::Gtk.Statusbar ();
		this.stdOutStatus.Name = "stdOutStatus";
		this.stdOutStatus.Spacing = 6;
		this.stdOutStatus.HasResizeGrip = false;
		// Container child stdOutStatus.Gtk.Box+BoxChild
		this.watchButton = new global::Gtk.Button ();
		this.watchButton.CanFocus = true;
		this.watchButton.Name = "watchButton";
		this.watchButton.UseUnderline = true;
		this.watchButton.Label = global::Mono.Unix.Catalog.GetString ("Watch");
		this.stdOutStatus.Add (this.watchButton);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.stdOutStatus [this.watchButton]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		this.vbox2.Add (this.stdOutStatus);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.stdOutStatus]));
		w44.Position = 2;
		w44.Expand = false;
		w44.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 510;
		this.DefaultHeight = 203;
		this.hpaned1.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenURLAction.Activated += new global::System.EventHandler (this.OpenURL);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnQuit);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAbout);
		this.button2.Clicked += new global::System.EventHandler (this.AddStream);
		this.button4.Clicked += new global::System.EventHandler (this.RemoveStream);
		this.addPlayerButton.Clicked += new global::System.EventHandler (this.EditPlayers);
		this.watchButton.Clicked += new global::System.EventHandler (this.WatchSelectedStream);
	}
}
